### ISSUE TITLE
Hash mdp client side

### ISSUE THREAD

**Issue by madelahay** [dropy-project/front#340]
# Hash de password coté front / ISSUE BLOQUANTE

Actuellement, les mots de passe de l'onboarding circulent en clair dans les requêtes vers le backend. On pourrais croire que ca ne change rien, mais en fait si, énormément.

Pourquoi on hash AVANT d'envoyer au backend et avant d'envoyer une requête ?

En fait on pourrais penser que vu que on le hash en BD on est protégé, mais non. 

Prenons un exemple simple. Je suis un attaquant, et un des utilisateur est connecte à un hotspot que je contrôle, ou alors je me suis placé en man in the middle entre son appareil et le serveur de dropy... Et ba je vois toutes les requêtes qui passent dans un sens ET dans l'autre, donc si le mec envoie une requête : 

/register
username=XXX
password=XXX

et reçoit comme réponse

HTTP 200 ok

baaaa en fait l'attaquant viens juste de lui sucrer son password tranquillement. 

Dans le cas contraire si le frontend hash le password (HASH pas chiffre !) il est impossible meme en voyant toutes les requêtes d'avoir le password, qu'il soit erroné ou non.

## Tasks

- [ ] Modifier la méthode d'authentification pour hash le password dans le front avant de l'envoyer au back
- [ ] Verifier avec le back si eux arrêtent de hash le password une fois qu'ils le reçoivent et considèrent bien qu'ils reçoivent un password déjà hash
- [x] utiliser une méthode de hash non vulnérable ( cf plus bas )
- [ ] "salting / compliquer" le hash (en front dire salt ca me fait mal mais pas grave tkt insh)

## Hash vulnérables c'est possible ca ?

En fait oui certaines méthodes sont vulnérables et deprecated, comme le MD5 ou le SHA1.

Il faut donc préférer les méthodes de hash type SHA256 ou SHA512 (si trouvable en 512, à préférer, mais protocole pas tjrs stable, voyez pour votre cas sur la doc ).

## Le salting de hash

Quand on compute un hash, un algo passe en fait sur notre chaine pour la transformer en une chaine unique NORMALEMENT indéchiffrable. Soyons honnêtes cela dit, sur les mots de passe courants, les chaines sont connues. En fait, étant donné que 1chaine=1hash sans variation possible (unicité des ensembles), il est possible d'essayer de compute tous les hashs possibles et imaginables pour ensuite bruteforce une appli. Exemple, on sait que les 3 mots de passe les plus utilisés dans le monde son lui lui et lui, on les hash dans le protocole utilisé par l'app, genre SHA256, et hop on à le hash du mot de passe de l'user, et si on intercepte la requête et que le hash est égal au notre, alors on a le password par correspondance direct.

Comment on empêche ca me direz vous ? Déjà en utilisant un algo de hash pas facile à crack pasque trop chiant à énumérer, et ensuite en salant les hash.

Le salting, ca consiste à ajouter une layer au dessus de notre hash. En fait, le front vas hasher le password, et ajouter par dessus un algo maison, en gros ajouter quelques caractères de plus par ci par la.

Exemple : 

password=1234
hash=examplehash
saltedHash=hash+"56hsa1"

Donc meme si le mec à hash de son coté 1234 et sait que ca fait "examplehash" quand il vas vouloir comparer il vas comparer à "exemplehash56hsa1" donc il ne sait pas que c'est 1234 derrière pasque c pas le meme hash. Vous me direz, si le hash est hardcode dans le front c'est pas compliqué pour le mec de le trouver, l'enlever du hash et refaire sa manip ou il compare des hash. Alors oui, mais ca aussi on peut l'éviter ;)

Dans le principe pour ne pas que ce salt soit fixe :

On crée une méthode qui génère un hash en fonction du Password, pendant la phase de register ET de login, sinon le back ne saura pas déchiffrer. L'idée ici pour ne pas se casser la tete est de hash un hash dans deux méthodes différentes. Par ce principe, si l'attaquant veux comparer les hash il lui faudra le premier, qu'il ne peut avoir qu'en le comparant au deuxième, et autant dire que comparer le hash du hash d'un mot de passe, GLHF, sauf si le mec à envie de se péter les rouleaux à compute des hash de hash à la main...

EN GROS : (et avec un exalgo approximatif)

begin
{
|    password=form.getPassword()
|    
|    procédure generateHashSalted(password); returning string : hashedSaltedPassword {
|    |
|    |    hashOne : string <- computeSha256Hash(password)
|    |    hashTwo : string <- computeBCryptHash(hashOne)
|    |    
|    |    return hashTwo as hashedSaltedPassword
|    |
|    }
|    
|    return(HTTPResponse.add(generateHashSalted(password));
|
}end
